# Generated by Django 4.2.9 on 2025-02-03 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('follower', '0003_alter_notification_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
    ]
