# Generated by Django 4.2.9 on 2025-06-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_otpcode_created_alter_passwordresettoken_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='I2JoMD23yvHv1l9cn0vMqm1CImSqBihHF92rCLkdT0oP76s3JBzIpPyTprRiheciz8Ciy5n6uofnacjApFtELdi0vHr3AcTEMFpPfgKZwkQUYgmWEbE1u88lkm0S5nGm9YXt6trlJ7NdQORZ3CX1QiL5mZBiNlu5aJ64EQDmdgrhE9UV7pN6oikfciYVUXV7VbeCf4Ts2r6RTzmgUATinNIPaJsuvSWx9MqX2Q6LtexZOBN9Bg4CiG4d9C1cE9XQ', max_length=300, unique=True),
        ),
    ]
