# Generated by Django 4.2.9 on 2025-06-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0007_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='3x6iEGdaGqMzSHup2RBrgfNs0kTFDZkh8dczrZHiFQvizp33LkFgLCE4F5MmTXlLFk9a2o4uOjAjFLWWUYvMS8KKydcLUVLeTB7j5RJz9pOv5EQvRfg5N7UO3FxaRtUr0wf8aC4HWdVVWkl07XygxkmutfLTQ8CYaXhj8KaS6e71S23cpqSYDaduQiUsGM9TjTZQ73yfFsIzjnqrpIKnvZ3DbakkuaLJww4g574WWR4CvCJQZbBsz7h5ekjG7cdL', max_length=300, unique=True),
        ),
    ]
