# Generated by Django 4.2.9 on 2025-06-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0008_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='Wu3Yb3DMEim79MR9S9Sc4ff2yZB57SiVnVAEvsc3UvLgVQOn1JVJan7LHvEAYeojLLZ2u1g6HqK3AJfupIEtMe62IM6qL8FMx1wSwUEwyjx7zt2wADxqDPgTAbDbAbOAHHOmzbARHibLW1QLdzoWtzSgs1WgD5KFIhk2qnl7rv7pvUZoorLVgBisaxXDpclg0KnHM42yBQyYGpSmc4giCWVhUtFGfnpZ19T3bKxPDv9mRIWWNVn343HabQq8lTpf', max_length=300, unique=True),
        ),
    ]
