# Generated by Django 4.2.9 on 2024-10-31 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 31, 17, 59, 7, 634906, tzinfo=datetime.timezone.utc)),
        ),
    ]
