# Generated by Django 4.2.9 on 2025-01-21 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_comment_created_alter_likepost_created_and_more'),
        ('follower', '0002_alter_follower_followed_alter_follower_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='post'),
        ),
    ]
